/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dluha
 */
import java.sql.Connection;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
public class checkin extends javax.swing.JFrame {
String tv,wf,tgl,nama;

    /**
     * Creates new form checkin
     */
    public void tanggal(){
        Date d = new Date();
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
     tgl = sdf.format(d);
    }
       public void kamar(){
           try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();
            String query = "SELECT * FROM kamar";
            ResultSet rs = s.executeQuery(query);
             
            while (rs.next()) {                
                cbkamar.addItem(rs.getString("idkamar"));
            }
             
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
             
        } catch (SQLException e) {
        }
    }
              public void tamu(){
           try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();
            String query = "SELECT * FROM tamu";
            ResultSet rs = s.executeQuery(query);
             
            while (rs.next()) {                
                cbtamu.addItem(rs.getString("idtamu"));
            }
             
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
             
        } catch (SQLException e) {
        }
    }
    public checkin() {
        initComponents();
        kamar();
        tamu();
        tanggal();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbkamar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbtamu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tivi = new javax.swing.JRadioButton();
        wifi = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PILIH KAMAR");

        cbkamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH KAMAR" }));
        cbkamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkamarActionPerformed(evt);
            }
        });

        jLabel2.setText("NAMA PENGUNJUNG");

        cbtamu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAMA TAMU" }));
        cbtamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtamuActionPerformed(evt);
            }
        });

        jLabel3.setText("FASIITAS TAMBAHAN");

        tivi.setText("TELEVISI");
        tivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiviActionPerformed(evt);
            }
        });

        wifi.setText("WIFI");
        wifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wifiActionPerformed(evt);
            }
        });

        jButton1.setText("CHECK IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("KELUAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tivi)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(wifi)))
                    .addComponent(cbtamu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbkamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbkamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbtamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tivi)
                    .addComponent(wifi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbkamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkamarActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_cbkamarActionPerformed

    private void cbtamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtamuActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_cbtamuActionPerformed

    private void tiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiviActionPerformed
        if (tivi.isSelected()){
           tv = "ya";
        }else{
           tv = "tidak";
        }   // TODO add your handling code here:
    }//GEN-LAST:event_tiviActionPerformed

    private void wifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wifiActionPerformed
            if (wifi.isSelected()){
            wf = "ya";
        }else{
            wf = "tidak";
        }        // TODO add your handling code here:
    }//GEN-LAST:event_wifiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String sql = "INSERT INTO checkin (idkamar,idtamu,tgl_in,tv,wifi) VALUES ('"+ cbkamar.getSelectedItem() +"','"+ cbtamu.getSelectedItem() +"','"+tgl+"','"+tv+"','"+wf+"')";
            java.sql.Connection conn=(Connection)KoneksiDatabase.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbkamar;
    private javax.swing.JComboBox<String> cbtamu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton tivi;
    private javax.swing.JRadioButton wifi;
    // End of variables declaration//GEN-END:variables
}
